- name: Testing filters through ansible playbook 
  hosts: localhost
  become: yes
  vars:
   NAME: Siva Reddy Medam
  tasks:
   - name: convert into upper case
     debug:
      msg: "Hello {{NAME | upper}}"
   - name: convert into lower case
     debug:
      msg: "Hello {{NAME | lower}}"
   - name: printing undefined variable
     debug:
      msg: "Course is :{{COURSE | default('DevOps')}}"