- name: Testing filters through ansible playbook 
  hosts: centos:ubuntu
  become: yes
  vars:
   NAME: Siva Reddy Medam
  tasks:
   - name: convert into upper case
     debug:
      msg: "Hello {{NAME | upper}}"